services:
  comfyui:
    image: ezycloudx/comfyui:cuda12.6
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
      - ./custom_nodes:/app/ComfyUI/custom_nodes
      - ./models:/app/ComfyUI/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped