version: "3.8"
services:
  comfyui:
    image: thanhlam00290/comfyui
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./data:/app/data:rw
      - ./input:/app/ComfyUI/input:rw
      - ./output:/app/ComfyUI/output:rw
      - ./custom_nodes:/app/ComfyUI/custom_nodes:rw
      - ./models:/app/ComfyUI/models:rw
    environment:
      - HF_AUTO_DOWNLOAD=0
      - HF_TOKEN=${HF_TOKEN:-}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - ./:/srv
      - ./database/filebrowser.db:/database/filebrowser.db
    restart: unless-stopped

  # Cloudflare Tunnel cho ComfyUI
  cloudflared-comfyui:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-comfyui
    command: tunnel --no-autoupdate --url http://comfyui:8188
    restart: unless-stopped
    depends_on:
      - comfyui

  # Cloudflare Tunnel riêng cho Filebrowser
  cloudflared-filebrowser:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-filebrowser
    command: tunnel --no-autoupdate --url http://filebrowser:80
    restart: unless-stopped
    depends_on:
      - filebrowser